#!/bin/sh

sudo dpkg -r python-gmtpy
sudo rm  *.deb && sudo rm -r ./build

python setup.py config build

sudo checkinstall -D --pkgname=python-gmtpy --pkgversion=0:0.1-dev-git \
--provides=python-gmtpy --default --backup=no \
--deldoc=yes --deldesc=yes --delspec=yes \
--fstrans=no \
python setup.py install
